# Generated by Django 5.0.3 on 2024-05-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_remove_patient_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[(1, '9am-10am'), (2, '10am-11am'), (3, '11am-12am'), (4, '12pm-1pm'), (5, '3pm-4pm'), (6, '4pm-5pm'), (7, '5pm-6pm')], max_length=20)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appointment.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Appointment.patient')),
            ],
        ),
    ]
