# Generated by Django 5.0.3 on 2024-05-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('1', '9am-10am'), ('2', '10am-11am'), ('3', '11am-12pm'), ('4', '12pm-1pm'), ('5', '3pm-4pm'), ('6', '4pm-5pm'), ('7', '5pm-6pm')], max_length=20),
        ),
    ]
