# Generated by Django 5.0.3 on 2024-05-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('9am-10am', '9am-10am'), ('10am-11am', '10am-11am'), ('11am-12pm', '11am-12pm'), ('12pm-1pm', '12pm-1pm'), ('3pm-4pm', '3pm-4pm'), ('4pm-5pm', '4pm-5pm'), ('5pm-6pm', '5pm-6pm')], max_length=20),
        ),
    ]
