# Generated by Django 5.0.6 on 2024-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_appointment_status_pharmacist_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='No_of_doctors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='.\\static\\images\\default-profile.jfif', upload_to='Userpics'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='.\\static\\images\\default-profile.jfif', upload_to='Userpics'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='profile_pic',
            field=models.ImageField(default='.\\static\\images\\default-profile.jfif', upload_to='Userpics'),
        ),
    ]
