# Generated by Django 5.0.6 on 2024-05-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0009_alter_departments_no_of_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='.\\images\\default-profile.jfif', upload_to='Userpics'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(default='.\\images\\default-profile.jfif', upload_to='Userpics'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='profile_pic',
            field=models.ImageField(default='.\\images\\default-profile.jfif', upload_to='Userpics'),
        ),
    ]
