# Generated by Django 5.0.6 on 2024-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_alter_doctor_profile_pic_alter_patient_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(upload_to='Userpics'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(upload_to='Userpics'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='profile_pic',
            field=models.ImageField(upload_to='Userpics'),
        ),
    ]
