# Generated by Django 5.0.6 on 2024-05-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0011_alter_doctor_profile_pic_alter_patient_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(upload_to='Userpics'),
        ),
    ]
