# Generated by Django 5.0.6 on 2024-06-08 18:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_bed'),
        ('Appointment', '0013_remove_doctor_department_remove_doctor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtype', models.CharField(choices=[('Ebed', 'Emergency'), ('Gbed', 'General')], max_length=20)),
                ('startdate', models.DateField(default=datetime.datetime.now)),
                ('enddate', models.DateField(default=datetime.datetime.now)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.patient')),
            ],
        ),
    ]
