# Generated by Django 5.0.6 on 2024-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0014_bedbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('9am-10am', '9am-10am'), ('10am-11am', '10am-11am'), ('11am-12pm', '11am-12pm'), ('12pm-1pm', '12pm-1pm'), ('3pm-4pm', '3pm-4pm'), ('4pm-5pm', '4pm-5pm'), ('5pm-6pm', '5pm-6pm'), ('6pm-7pm', '6pm-7pm')], max_length=20),
        ),
    ]
