# Generated by Django 5.0.6 on 2024-05-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_departments_doctor_patient_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(upload_to='Userpics'),
        ),
    ]
