# Generated by Django 5.0.6 on 2024-05-29 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_patient_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='shift',
        ),
        migrations.AddField(
            model_name='departments',
            name='phoneno',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phoneno',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneno',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='phoneno',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
