# Generated by Django 5.0.6 on 2024-06-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_doctor_shift_remove_pharmacist_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ebed', models.PositiveIntegerField(default=0)),
                ('Gbed', models.PositiveIntegerField(default=0)),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.departments')),
            ],
        ),
    ]
